apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cdc-outbox-event-producer
  description: Kotlin/JVM library that streams Postgres logical-replication outbox messages to AWS SNS/SQS (and, in the roadmap, Kafka/RabbitMQ/MySQL)
  annotations:
    github.com/project-slug: fernandoofj/cdc-outbox-event-producer
  labels:
    tier: T1
  tags:
    - kotlin
    - cdc
    - outbox
    - postgres
spec:
  type: library
  owner: fernandoofj
  lifecycle: experimental
