# spring
spring.datasource.host=${DB_HOST}
spring.datasource.port=${DB_PORT}
spring.datasource.database=${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# replication
replication.datasource.slot=${DB_SLOT_NAME}

# aws
cloud.aws.region.static=us-east-1
cloud.aws.credentials.access-key=test
cloud.aws.credentials.secret-key=test
cloud.aws.localstack.url=http://localhost:4566
